list = [{'ID': '15853', 'Name': 'B-52', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '14360', 'Name': 'Absolut Sex', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '12762', 'Name': 'Grizzly Bear', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '17200', 'Name': 'Grasshopper', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12446', 'Name': 'Veteran', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '13192', 'Name': 'National Aquarium', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '17226', 'Name': 'Adam & Eve', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '15330', 'Name': 'Orange Crush', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '12618', 'Name': 'Orangeade', 'Categories': 'Cocktail', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '11989', 'Name': 'Queen Charlotte', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '11000', 'Name': 'Mojito', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '12564', 'Name': 'Apple Karate', 'Categories': 'Cocktail', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball Glass'},
{'ID': '15403', 'Name': 'Vodka Russian', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '17830', 'Name': 'Corn n Oil', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '12800', 'Name': 'Coffee-Vodka', 'Categories': 'Homemade Liqueur', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '16485', 'Name': 'Flaming Lamborghini', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '17241', 'Name': 'Zombie', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Hurricane glass'},
{'ID': '16196', 'Name': 'Moranguito', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '13535', 'Name': 'Pink Panty Pulldowns', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '16985', 'Name': 'Shot-gun', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '17242', 'Name': 'Bombay Cassis', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Balloon Glass'},
{'ID': '17185', 'Name': 'Casino', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12712', 'Name': 'Grape lemon pineapple Smoothie', 'Categories': 'Other/Unknown', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '14860', 'Name': 'Talos Coffee', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Alcoholic', 'Glass': 'Brandy snifter'},
{'ID': '11008', 'Name': 'Manhattan', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11129', 'Name': 'Boston Sour', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Whiskey sour glass'},
{'ID': '12672', 'Name': 'Fruit Flip-Flop', 'Categories': 'Other/Unknown', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball Glass'},
{'ID': '15941', 'Name': 'Americano', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '12698', 'Name': 'Lassi - Mango', 'Categories': 'Other/Unknown', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '11005', 'Name': 'Dry Martini', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12138', 'Name': 'Scotch Cobbler', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '11324', 'Name': 'Dry Rob Roy', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11024', 'Name': 'Almond Joy', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12780', 'Name': 'Spiking coffee', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Non alcoholic', 'Glass': 'Coffee mug'},
{'ID': '14181', 'Name': 'Cafe Savoy', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Alcoholic', 'Glass': 'Coffee mug'},
{'ID': '14622', 'Name': 'Arctic Fish', 'Categories': 'Punch / Party Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Beer pilsner'},
{'ID': '17197', 'Name': 'French 75', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '11055', 'Name': 'Artillery', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '13042', 'Name': 'Sunny Holiday Punch', 'Categories': 'Punch / Party Drink', 'Alcoholic': 'Optional alcohol', 'Glass': 'Punch bowl'},
{'ID': '13807', 'Name': 'After Five', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '14053', 'Name': "Mother's Milk", 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '15675', 'Name': 'A midsummernight dream', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '11524', 'Name': 'Imperial Fizz', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '17211', 'Name': 'Dark and Stormy', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '11993', 'Name': 'Quentin', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12067', 'Name': 'Rum Cobbler', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '11993', 'Name': 'Quentin', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11662', 'Name': 'London Town', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '178317', 'Name': "Bee's Knees", 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Martini Glass'},
{'ID': '16108', 'Name': '9 1/2 Weeks', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12738', 'Name': 'Hot Chocolate to Die for', 'Categories': 'Cocoa', 'Alcoholic': 'Non alcoholic', 'Glass': 'Coffee mug'},
{'ID': '11102', 'Name': 'Black Russian', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '11124', 'Name': 'Boomerang', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11542', 'Name': 'Jack Rose Cocktail', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11872', 'Name': 'Orgasm', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '13058', 'Name': 'Wine Punch', 'Categories': 'Punch / Party Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '15300', 'Name': '3-Mile Long Island Iced Tea', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '11007', 'Name': 'Margarita', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '14071', 'Name': 'Belgian Blue', 'Categories': 'Soft Drink / Soda', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '16354', 'Name': 'Arizona Antifreeze', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '12690', 'Name': 'Lassi - A South Indian Drink', 'Categories': 'Other/Unknown', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball Glass'},
{'ID': '11022', 'Name': 'Allies Cocktail', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '17218', 'Name': 'Vesper', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '15182', 'Name': 'After sex', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '13825', 'Name': 'Midnight Manx', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '14195', 'Name': 'Snowball', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '15106', 'Name': 'Apello', 'Categories': 'Other/Unknown', 'Alcoholic': 'Non alcoholic', 'Glass': 'Collins Glass'},
{'ID': '12087', 'Name': 'Rum Milk Punch', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '13206', 'Name': 'Caipirissima', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '11034', 'Name': 'Angel Face', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '14133', 'Name': 'Cosmopolitan Martini', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail Glass'},
{'ID': '11288', 'Name': 'Cuba Libre', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '16485', 'Name': 'Flaming Lamborghini', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12732', 'Name': 'Chocolate Beverage', 'Categories': 'Cocoa', 'Alcoholic': 'Non alcoholic', 'Glass': 'Coffee mug'},
{'ID': '17831', 'Name': 'A Furlong Too Late', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '17249', 'Name': 'Pegu Club', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '15639', 'Name': 'Texas Sling', 'Categories': 'Milk / Float / Shake', 'Alcoholic': 'Alcoholic', 'Glass': 'Wine Glass'},
{'ID': '12656', 'Name': 'Banana Strawberry Shake', 'Categories': 'Milk / Float / Shake', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball Glass'},
{'ID': '17834', 'Name': 'Abbey Cocktail', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11129', 'Name': 'Boston Sour', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Whiskey sour glass'},
{'ID': '13621', 'Name': 'Tequila Sunrise', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '16134', 'Name': 'Absolutly Screwed Up', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '17215', 'Name': 'Spritz', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-Fashioned glass'},
{'ID': '15346', 'Name': '155 Belmont', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'White wine glass'},
{'ID': '15024', 'Name': 'Absolutely Cranberry Smash', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '16271', 'Name': 'The Evil Blue Thing', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '13202', 'Name': 'Flaming Dr. Pepper', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '11170', 'Name': 'Brandy Sour', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Whiskey sour glass'},
{'ID': '12744', 'Name': 'Microwave Hot Cocoa', 'Categories': 'Cocoa', 'Alcoholic': 'Non alcoholic', 'Glass': 'Coffee mug'},
{'ID': '12776', 'Name': 'Melya', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Non alcoholic', 'Glass': 'Coffee mug'},
{'ID': '12748', 'Name': 'Orange Scented Hot Chocolate', 'Categories': 'Cocoa', 'Alcoholic': 'Non alcoholic', 'Glass': 'Coffee mug'},
{'ID': '14107', 'Name': 'Absolut Summertime', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '17836', 'Name': 'Acapulco', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '13032', 'Name': 'Spiced Peach Punch', 'Categories': 'Punch / Party Drink', 'Alcoholic': 'Non alcoholic', 'Glass': 'Collins Glass'},
{'ID': '12442', 'Name': 'Vermouth Cassis', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '15997', 'Name': 'GG', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Optional alcohol', 'Glass': 'Collins Glass'},
{'ID': '13070', 'Name': 'Fahrenheit 5000', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '12988', 'Name': 'Mulled Wine', 'Categories': 'Punch / Party Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '15849', 'Name': 'Apricot punch', 'Categories': 'Punch / Party Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Punch bowl'},
{'ID': '11003', 'Name': 'Negroni', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '12784', 'Name': 'Thai Iced Coffee', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '12093', 'Name': 'Rum Sour', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Whiskey sour glass'},
{'ID': '11239', 'Name': 'Cherry Rum', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11028', 'Name': 'Amaretto Stinger', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12190', 'Name': 'Sherry Flip', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Nick and Nora Glass'},
{'ID': '17174', 'Name': 'Cherry Electric Lemonade', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Pint glass'},
{'ID': '11870', 'Name': 'Orange Oasis', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '12436', 'Name': 'Van Vleet', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '15024', 'Name': 'Absolutely Cranberry Smash', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12460', 'Name': 'Vodka And Tonic', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '11993', 'Name': 'Quentin', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '13423', 'Name': 'Atlantic Sun', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '17828', 'Name': 'Tipperary', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Nick and Nora Glass'},
{'ID': '11147', 'Name': 'Bourbon Sour', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Whiskey sour glass'},
{'ID': '15266', 'Name': 'Avalon', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '17241', 'Name': 'Zombie', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Hurricane glass'},
{'ID': '17835', 'Name': 'Abilene', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '11423', 'Name': 'Godfather', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '16275', 'Name': "Jack's Vanilla Coke", 'Categories': 'Other/Unknown', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '12808', 'Name': 'Creme de Menthe', 'Categories': 'Homemade Liqueur', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '12518', 'Name': 'Whisky Mac', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '11528', 'Name': 'Irish Spring', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '16987', 'Name': 'Irish Curdling Cow', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '15941', 'Name': 'Americano', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '11024', 'Name': 'Almond Joy', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '16295', 'Name': 'Bleeding Surgeon', 'Categories': 'Soft Drink / Soda', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '16986', 'Name': 'Bible Belt', 'Categories': 'Other/Unknown', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '12720', 'Name': 'Kill the cold Smoothie', 'Categories': 'Other/Unknown', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '11786', 'Name': 'Mississippi Planters Punch', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '11106', 'Name': 'Blackthorn', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11112', 'Name': 'Bloody Maria', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '15026', 'Name': 'Kiss me Quick', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '11242', 'Name': 'Chicago Fizz', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '178327', 'Name': 'Pineapple Paloma', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '14782', 'Name': 'Hot Creamy Bush', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Alcoholic', 'Glass': 'Irish coffee cup'},
{'ID': '17225', 'Name': 'Ace', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Martini Glass'},
{'ID': '13072', 'Name': 'Popped cherry', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '11472', 'Name': 'Hawaiian Cocktail', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11320', 'Name': 'Dragonfly', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '12560', 'Name': 'Afterglow', 'Categories': 'Cocktail', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball Glass'},
{'ID': '11120', 'Name': 'Bluebird', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '178322', 'Name': 'Spice 75', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Wine Glass'},
{'ID': '12916', 'Name': 'Egg Nog - Healthy', 'Categories': 'Punch / Party Drink', 'Alcoholic': 'Optional alcohol', 'Glass': 'Collins Glass'},
{'ID': '15006', 'Name': 'Turkeyball', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '17198', 'Name': 'French Connection', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '12196', 'Name': 'Sidecar', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11728', 'Name': 'Martini', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11993', 'Name': 'Quentin', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '17233', 'Name': 'Salted Toffee Martini', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12726', 'Name': 'Tomato Tang', 'Categories': 'Other/Unknown', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '17196', 'Name': 'Cosmopolitan', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '13625', 'Name': 'Screaming Orgasm', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12630', 'Name': 'Rail Splitter', 'Categories': 'Cocktail', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '11106', 'Name': 'Blackthorn', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '13535', 'Name': 'Pink Panty Pulldowns', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '14282', 'Name': 'California Root Beer', 'Categories': 'Soft Drink / Soda', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '12087', 'Name': 'Rum Milk Punch', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '15825', 'Name': 'Jamaican Coffee', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Alcoholic', 'Glass': 'Champagne flute'},
{'ID': '17141', 'Name': 'Smut', 'Categories': 'Punch / Party Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Beer mug'},
{'ID': '15515', 'Name': 'Tennesee Mud', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Alcoholic', 'Glass': 'Coffee Mug'},
{'ID': '13282', 'Name': 'Black & Tan', 'Categories': 'Beer', 'Alcoholic': 'Alcoholic', 'Glass': 'Pint glass'},
{'ID': '16262', 'Name': 'H.D.', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Alcoholic', 'Glass': 'Beer mug'},
{'ID': '17066', 'Name': 'Army special', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11369', 'Name': 'Flying Scotchman', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '16403', 'Name': 'Black and Brown', 'Categories': 'Beer', 'Alcoholic': 'Alcoholic', 'Glass': 'Beer pilsner'},
{'ID': '17114', 'Name': 'Ruby Tuesday', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '11255', 'Name': 'Clove Cocktail', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '15743', 'Name': 'Fuzzy Asshole', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Alcoholic', 'Glass': 'Coffee mug'},
{'ID': '11985', 'Name': 'Quarter Deck Cocktail', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '13625', 'Name': 'Screaming Orgasm', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12434', 'Name': 'Valencia Cocktail', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '14598', 'Name': '50/50', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '17210', 'Name': 'Bramble', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-Fashioned glass'},
{'ID': '14095', 'Name': 'Jamaica Kiss', 'Categories': 'Milk / Float / Shake', 'Alcoholic': 'Alcoholic', 'Glass': 'Hurricane glass'},
{'ID': '12752', 'Name': 'Lemon Shot', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '11403', 'Name': 'Gin And Tonic', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '15597', 'Name': 'Absolut Stress #2', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '14602', 'Name': 'Tequila Surprise', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '11390', 'Name': 'Frozen Mint Daiquiri', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '15328', 'Name': 'Zorro', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Alcoholic', 'Glass': 'Coffee Mug'},
{'ID': '15423', 'Name': '110 in the shade', 'Categories': 'Beer', 'Alcoholic': 'Alcoholic', 'Glass': 'Beer Glass'},
{'ID': '11938', 'Name': 'Pink Lady', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11106', 'Name': 'Blackthorn', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '178307', 'Name': 'Tequila Slammer', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Hurricane glass'},
{'ID': '13501', 'Name': 'ABC', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '15825', 'Name': 'Jamaican Coffee', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Alcoholic', 'Glass': 'Champagne flute'},
{'ID': '14510', 'Name': "Bailey's Dream Shake", 'Categories': 'Soft Drink / Soda', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '16289', 'Name': 'Apple Grande', 'Categories': 'Punch / Party Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Punch Bowl'},
{'ID': '12726', 'Name': 'Tomato Tang', 'Categories': 'Other/Unknown', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '17190', 'Name': 'Paradise', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11164', 'Name': 'Brandy Flip', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Whiskey sour glass'},
{'ID': '12572', 'Name': 'Bora Bora', 'Categories': 'Cocktail', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '11407', 'Name': 'Gin Cooler', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '16963', 'Name': 'Zorbatini', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12190', 'Name': 'Sherry Flip', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Nick and Nora Glass'},
{'ID': '12188', 'Name': 'Sherry Eggnog', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '17228', 'Name': 'Addison', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Martini Glass'},
{'ID': '178322', 'Name': 'Spice 75', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Wine Glass'},
{'ID': '12107', 'Name': 'Salty Dog', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '15106', 'Name': 'Apello', 'Categories': 'Other/Unknown', 'Alcoholic': 'Non alcoholic', 'Glass': 'Collins Glass'},
{'ID': '11008', 'Name': 'Manhattan', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12914', 'Name': 'Egg-Nog - Classic Cooked', 'Categories': 'Punch / Party Drink', 'Alcoholic': 'Optional alcohol', 'Glass': 'Pitcher'},
{'ID': '12572', 'Name': 'Bora Bora', 'Categories': 'Cocktail', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '16419', 'Name': 'Avalanche', 'Categories': 'Milk / Float / Shake', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '17227', 'Name': 'Addington', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '13198', 'Name': 'Quick F**K', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '16958', 'Name': 'Apple Pie with A Crust', 'Categories': 'Other/Unknown', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '11987', 'Name': 'Queen Bee', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11542', 'Name': 'Jack Rose Cocktail', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11243', 'Name': 'Chocolate Black Russian', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Champagne flute'},
{'ID': '17233', 'Name': 'Salted Toffee Martini', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11157', 'Name': 'Brandy Cobbler', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '15511', 'Name': 'Baby Eskimo', 'Categories': 'Milk / Float / Shake', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '14071', 'Name': 'Belgian Blue', 'Categories': 'Soft Drink / Soda', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '16275', 'Name': "Jack's Vanilla Coke", 'Categories': 'Other/Unknown', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '13395', 'Name': 'Bob Marley', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '11728', 'Name': 'Martini', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12784', 'Name': 'Thai Iced Coffee', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '17829', 'Name': 'Penicillin', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '12890', 'Name': 'Cranberry Punch', 'Categories': 'Punch / Party Drink', 'Alcoholic': 'Non alcoholic', 'Glass': 'Punch Bowl'},
{'ID': '13068', 'Name': 'Brave Bull Shooter', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '16998', 'Name': 'Bruised Heart', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '17230', 'Name': 'Gin Rickey', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '17220', 'Name': 'Butter Baby', 'Categories': 'Milk / Float / Shake', 'Alcoholic': 'Alcoholic', 'Glass': 'Beer mug'},
{'ID': '15288', 'Name': '252', 'Categories': 'Shot', 'Alcoholic': 'Alcoholic', 'Glass': 'Shot glass'},
{'ID': '12672', 'Name': 'Fruit Flip-Flop', 'Categories': 'Other/Unknown', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball Glass'},
{'ID': '11728', 'Name': 'Martini', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12162', 'Name': 'Screwdriver', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '12730', 'Name': 'Castillian Hot Chocolate', 'Categories': 'Cocoa', 'Alcoholic': 'Non alcoholic', 'Glass': 'Coffee mug'},
{'ID': '17005', 'Name': 'A True Amaretto Sour', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '17829', 'Name': 'Penicillin', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '12790', 'Name': 'Absinthe #2', 'Categories': 'Homemade Liqueur', 'Alcoholic': 'Alcoholic', 'Glass': 'Jar'},
{'ID': '14364', 'Name': 'Aztec Punch', 'Categories': 'Punch / Party Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Punch bowl'},
{'ID': '17828', 'Name': 'Tipperary', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Nick and Nora Glass'},
{'ID': '12776', 'Name': 'Melya', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Non alcoholic', 'Glass': 'Coffee mug'},
{'ID': '13499', 'Name': 'Oreo Mudslide', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '13938', 'Name': 'AT&T', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball Glass'},
{'ID': '17838', 'Name': 'Adonis Cocktail', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '16447', 'Name': "Brandon and Will's Coke Float", 'Categories': 'Soft Drink / Soda', 'Alcoholic': 'Alcoholic', 'Glass': 'Beer mug'},
{'ID': '16311', 'Name': 'Applejack', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11320', 'Name': 'Dragonfly', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '12322', 'Name': 'Strawberry Margarita', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11239', 'Name': 'Cherry Rum', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '14598', 'Name': '50/50', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '17074', 'Name': 'Arizona Twister', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Hurricane glass'},
{'ID': '11433', 'Name': 'Grass Skirt', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '12770', 'Name': 'Iced Coffee', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Non alcoholic', 'Glass': 'Coffee mug'},
{'ID': '14378', 'Name': 'Lunch Box', 'Categories': 'Beer', 'Alcoholic': 'Alcoholic', 'Glass': 'Pint glass'},
{'ID': '11416', 'Name': 'Gin Smash', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '11938', 'Name': 'Pink Lady', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11064', 'Name': 'Banana Daiquiri', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Champagne flute'},
{'ID': '15184', 'Name': 'San Francisco', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '14860', 'Name': 'Talos Coffee', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Alcoholic', 'Glass': 'Brandy snifter'},
{'ID': '15300', 'Name': '3-Mile Long Island Iced Tea', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '17208', 'Name': 'Rose', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '17194', 'Name': 'White Lady', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '17195', 'Name': 'Bellini', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Champagne Flute'},
{'ID': '13499', 'Name': 'Oreo Mudslide', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '12091', 'Name': 'Rum Screwdriver', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '14157', 'Name': 'Ziemes Martini Apfelsaft', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '17218', 'Name': 'Vesper', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '17044', 'Name': 'Homemade Kahlua', 'Categories': 'Homemade Liqueur', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
{'ID': '178316', 'Name': 'Honey Bee', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Margarita glass'},
{'ID': '12746', 'Name': 'Nuked Hot Chocolate', 'Categories': 'Cocoa', 'Alcoholic': 'Non alcoholic', 'Glass': 'Coffee mug'},
{'ID': '17181', 'Name': 'Dirty Martini', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11146', 'Name': 'Bourbon Sling', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '17108', 'Name': 'Coke and Drops', 'Categories': 'Soft Drink / Soda', 'Alcoholic': 'Non alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '15226', 'Name': 'Space Odyssey', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '15515', 'Name': 'Tennesee Mud', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Alcoholic', 'Glass': 'Coffee Mug'},
{'ID': '178325', 'Name': 'Aperol Spritz', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Wine Glass'},
{'ID': '12722', 'Name': 'Strawberry Shivers', 'Categories': 'Other/Unknown', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '11026', 'Name': 'Amaretto Mist', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '14456', 'Name': 'Kurant Tea', 'Categories': 'Coffee / Tea', 'Alcoholic': 'Alcoholic', 'Glass': 'Champagne flute'},
{'ID': '17210', 'Name': 'Bramble', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-Fashioned glass'},
{'ID': '12760', 'Name': 'Surf City Lifesaver', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '12720', 'Name': 'Kill the cold Smoothie', 'Categories': 'Other/Unknown', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '11054', 'Name': 'Arthur Tompkins', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Whiskey sour glass'},
{'ID': '11670', 'Name': 'Lord And Lady', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '12766', 'Name': 'Happy Skipper', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '17229', 'Name': 'Adios Amigos Cocktail', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Martini Glass'},
{'ID': '11600', 'Name': 'Kamikaze', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11034', 'Name': 'Angel Face', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11403', 'Name': 'Gin And Tonic', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '17250', 'Name': 'Corpse Reviver #2', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12734', 'Name': 'Chocolate Drink', 'Categories': 'Cocoa', 'Alcoholic': 'Non alcoholic', 'Glass': 'Coffee mug'},
{'ID': '14065', 'Name': "Zippy's Revenge", 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '17192', 'Name': 'Porto flip', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11146', 'Name': 'Bourbon Sling', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '11004', 'Name': 'Whiskey Sour', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '11963', 'Name': 'Port Wine Cocktail', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '12067', 'Name': 'Rum Cobbler', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '178315', 'Name': 'Munich Mule', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Highball glass'},
{'ID': '12198', 'Name': 'Sidecar Cocktail', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '11003', 'Name': 'Negroni', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Old-fashioned glass'},
{'ID': '17196', 'Name': 'Cosmopolitan', 'Categories': 'Cocktail', 'Alcoholic': 'Alcoholic', 'Glass': 'Cocktail glass'},
{'ID': '13128', 'Name': 'Diesel', 'Categories': 'Beer', 'Alcoholic': 'Alcoholic', 'Glass': 'Pint glass'},
{'ID': '12630', 'Name': 'Rail Splitter', 'Categories': 'Cocktail', 'Alcoholic': 'Non alcoholic', 'Glass': 'Highball glass'},
{'ID': '17120', 'Name': 'Brain Fart', 'Categories': 'Punch / Party Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Punch bowl'},
{'ID': '16295', 'Name': 'Bleeding Surgeon', 'Categories': 'Soft Drink / Soda', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins glass'},
{'ID': '12762', 'Name': 'Grizzly Bear', 'Categories': 'Ordinary Drink', 'Alcoholic': 'Alcoholic', 'Glass': 'Collins Glass'},
]

idlist = []
new_list = []
for lst in list:
    if lst["ID"] not in idlist:
        idlist.append(lst["ID"])
        new_list.append(lst)

print(len(new_list))
for i in new_list:
    print(i)